[package]
name = "ns-schedule"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = "0.10.12"
ns-log = {path = "../ns-log" }
thiserror = "1.0.30"
log = "0.4.15"
anyhow = "1.0.56"